[package]
name = "network-direct"
version = "0.1.0"
edition = "2024"

[dependencies]
windows-core = "0.61.2"
windows = { version = "0.61.3", features = [
    "Win32_Networking_WinSock",
    "Win32_System_Environment",
    "Win32_System_LibraryLoader",
    "Win32_System_Com",
    "Win32_System_Threading",
    "Win32_Security"
] }
network-direct-sys = { path = "../network-direct-sys", version = "0.1.0" }
bitflags = "2.9.1"
clap = { version = "4.5.40", features = ["derive"] }
winapi = { version = "0.3.9", features = ["ioapiset", "winsock2", "handleapi"] }
